baseURL = "https://kotohazi.netlify.app/"
title = "ことはじ"

enableRobotsTXT = true

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
theme = ["docsy"]

# Will give values to .Lastmod etc.
enableGitInfo = true

# Language settings
contentDir = "content/ja"
defaultContentLanguage = "ja"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

disableKinds = ["taxonomy", "taxonomyTerm"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# Configure how URLs look like per section.
[permalinks]
blog = "/:section/:year/:month/:day/:slug/"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
plainIDAnchors = true
hrefTargetBlank = true
angledQuotes = false
latexDashes = true
extensions = ["definitionLists"]

# Image processing configuration.
[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "UA-126571045-2"

# Language configuration

[languages]
[languages.ja]
title = "ことはじ"
description = "言オリについてまとめました"
languageName ="日本語"
contentDir = "content/ja"
time_format_default = "2006年01月02日"
time_format_blog = "2006年01月02日"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Everything below this are Site Params

[params]
copyright = "国際言語学オリンピック日本有志の会？"
cclicense = "by"

# First one is picked as the Twitter card image if not set on page.
images = ["images/logo.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://example.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/fulfom/kotohazi"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.


# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# Netlify functions
OgpApiEndpoint = "https://kotohazi.netlify.com/.netlify/functions/getOGP?url="

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = true

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'ありがとうございます！良ければ<a href="https://github.com/fulfom/kotohazi/issues/new">改善点を教えてください</a>.'
no = 'ごめんなさい！良ければ<a href="https://github.com/fulfom/kotohazi/issues/new">改善点を教えてください</a>.'

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
#[[params.links.user]]
#	name = "User mailing list"
#	url = "https://example.org/mail"
#	icon = "fa fa-envelope"
 #       desc = "Discussion and help from your fellow users"
[[params.links.user]]
	name ="Twitter"
	url = "https://twitter.com/fulfom"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter to get the latest news!"
#[[params.links.user]]
#	name = "Stack Overflow"
#	url = "https://example.org/stack"
#	icon = "fab fa-stack-overflow"
 #       desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/fulfom/kotohazi"
	icon = "fab fa-github"
        desc = "Development takes place here!"
#[[params.links.developer]]
#	name = "Slack"
#	url = "https://example.org/slack"
#	icon = "fab fa-slack"
 #       desc = "Chat with other project developers"
#[[params.links.developer]]
#	name = "Developer mailing list"
#	url = "https://example.org/mail"
#	icon = "fa fa-envelope"
 #       desc = "Discuss development issues around the project"

# 執筆陣のプロフィール
[[params.devs]]
	name = "fulfom"
	twitter = "https://twitter.com/fulfom"

[params.prob]
[[params.prob.1venue]]
	name = "出題元"
	datakey = "venue"
	value = ["IOL","APLO","JOL","Onling","海外予選","kotohazi","非LO"]
[[params.prob.2year]]
	name = "年"
	datakey = "year"
[[params.prob.3team]]
	name = "個人戦・団体戦"
	value = ["個人","団体"]
	datakey = "team"
[[params.prob.4difficulty]]
	name = "難易度"
	datakey = "difficulty"
	value = ["★1","★2","★3","★4","★5","★6","★7","★8","★未定"]
[params.diffstar]
	value = ["","★☆☆☆☆","★★☆☆☆","★★★☆☆","★★★★☆","★★★★★","<span class='bigstar'>★</span> ","<span class='bigstar'>★★</span> ","<span class='bigstar'>★★★</span> "]
[params.probCategory]
	name = "ジャンル"
	subname = ""
	value = ["統語","形態","音韻","韻律","文字","命数","意味"]
[[params.categoryForCompatiability]]
	name = "†語対応"
	query = ".意味.対応"
[[params.utility]]
	id = "translation"
	query = ".translation"
	value = "日本語版"
	stack = true
	icon = ["comment sort-utility-translation fa-lg","~訳"]
[[params.utility]]
	id = "hint"
	query = ".hint"
	value = "ヒント"
	icon = "lightbulb"
	color = "var(--yellow)"
[[params.utility]]
	id = "expl"
	query = ".expl"
	value = "解説付き"
	icon = "chalkboard-teacher"
[[params.utility]]
	id = "done"
	class = "uti-private"
	query = ".done"
	value = "挑戦済み"
	icon = "check-square"
[[params.utility]]
	id = "notdone"
	class = "uti-private"
	query = ":not(.done)"
	stack = true
	icon = ["check-square sort-utility-done","slash"]
[[params.utility]]
	id = "like"
	class = "uti-private"
	query = ".like"
	value = "お気に入り"
	icon = "heart"
#[[params.utility]]
#	id = "notlike"
#   class = "uti-private"
#	query = ":not(.like)"
#	stack = true
# 	icon = ["heart sort-utility-like","slash"]
[params.sort]
[[params.sort.1year]]
	dataSortBy = "year-venue-team-num"
	name = "年"
[[params.sort.2title]]
	dataSortBy = "title"
	name = "題名"
[[params.sort.3difficulty]]
	dataSortBy = "difficulty"
	name = "難易度"
[params.venuedetail]
	'海外予選' = "oversea"
	'非LO' = "nonlo"
[params.namedyear]
	-1 = "sample"
[params.pagetype]
	level = "star"
	stage = "flag"
	solve = "pen"
	know = "book-open"
	magic = "hat-wizard"
	hard = "dragon"
	refs = "book"
	prob = "lightbulb"
	person = "address-card"
	material = "icons"
	default = "file"

[params.login]
	login_url = "/login/"